### ISSUE TITLE
请问demo使用presto时报错，是什么原因呢

### ISSUE THREAD

**Issue by KnowledgeBeggar** [jcodeing/K-Sonic#1]
java.lang.UnsatisfiedLinkError: dlopen failed: library &quot;/system/lib/libsonic.so&quot; needed or dlopened by &quot;/system/lib/libnativeloader.so&quot; is not accessible for the namespace &quot;classloader-namespace&quot;

**Comment by jcodeing** [comment]
该项目不再维护, 请转
https://github.com/jcodeing/KMedia
https://github.com/jcodeing/ExoPlayer
